name: Security Scan

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Security Tool
        uses: kaiqui/security-tools-action@master
        with:
          tool: iac
          g_token: ${{ secrets.G_TOKEN }}
          g_username: ${{ secrets.G_USERNAME }}
